### ISSUE TITLE
ci: setup git hooks

### ISSUE THREAD

**Issue by gvieira18** [basementdevs/twitch-better-profile#51]
### Summary

Currently, our repo doesn't use [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) for extra checks before dev pushes the code.
I was trying to find a language-agnostic tool aka "binary tool" to manage these hooks.

If anyone has a suggestion for a different tool or approach, feel free to leave a comment.

### Here are some things to consider

- Impact on ease of development and onboarding.
- Balancing uniformity across the repo with the need for language-specific tools.
- Long-term manageability, including updates and changes.

### [lefthook](https://github.com/evilmartians/lefthook) Approaches

![image](https://github.com/user-attachments/assets/7926c9d1-3a1a-4dcd-9ff0-77037667f8d5)

#### Using `lefthook` as a Global Binary

- Simplifies hook management but requires manual setup on each machine.
- Global installation depends on OS and architecture, which can be managed with setup scripts (e.g., `Makefile`).
- Ensures consistent hook management across all projects without unnecessary dependencies.
- Developers need to manually install `lefthook`, which could be a hurdle if not automated.

#### Installing `lefthook` via `pnpm` in the `extension` directory

- Centralizes hook management but adds overhead for non-JS developers.
- Requires developers working in other parts of the repo to install `pnpm` and its dependencies, even if they don't work on the `extension` part.
- Ensures that `lefthook` and its configuration are consistently managed within the repo, leveraging existing Node.js tools.
- Developers focused on non-JavaScript projects (like Rust) must install `pnpm` and related dependencies, which might be irrelevant to their work.

#### Using Simple `package.json` in Root Folder to Manage Hooks and Dependencies

- A minimal `package.json` in the root folder is used solely to manage Git hooks and dependencies across the repo.
- This approach centralizes hook management in a single location, but may introduce unnecessary Node.js (`pnpm`) dependencies to non-JavaScript projects.
- Simplifies setup by consolidating all Git hooks in one place, making it easier to maintain and update.
- Requires all developers to have Node.js installed, even if they don't work with JavaScript, adding potentially irrelevant dependencies to non-JS projects.

#### Don't Use Git Hooks and Rely Only on CI Pipeline for Pull Requests

- Relies entirely on CI, reducing local complexity but potentially slowing feedback.
- Developers don't need to manage or configure Git hooks, simplifying local development environments.
- Developers may depend entirely on the CI pipeline for detecting issues, which can delay feedback and slow down the development process.

#### Separate Repos by Language

- Simplifies individual setups but complicates cross-project coordination.
- Each language or project has its own repository, simplifying dependency management but potentially complicating cross-project coordination.
- Developers only manage and install dependencies relevant to their specific language or project.
- Managing multiple repositories can complicate cross-project integration and collaboration.

**Comment by gvieira18** [comment]
links: basementdevs/tbp-extension#1

**Comment by DanielHe4rt** [comment]
Still missing the tbp-platform and tbp-consumer but here's my recommendations:

- At Laravel we can use the Default provided by Laravel Pint and also add a simple PHPStan (Larastan) to make it even better. 
- At Rust, would be better check with @Daniel-Boll how to make it work without hooks. If I remember well he made a rustfmt file that we gonna have to check how to add to each IDE.

**Comment by gvieira18** [comment]
Related: basementdevs/tbp-consumer-api#2

**Comment by gvieira18** [comment]
Related: basementdevs/tbp-platform#2
