### ISSUE TITLE
feat: v1 UI

### ISSUE THREAD

**Issue by moovmooov** [basementdevs/twitch-better-profile#58]
# V1

![pqp front-end é chato pra caralho](https://github.com/user-attachments/assets/ec304435-a5c2-480b-8aca-a67853a61a03)

This issue tracks the implementation of V1, focusing on UI enhancements and feature completions. Below is a detailed todo list of the UI components and their current status.

## Screens

- [x]  Theme Setup

- Authenticate
  - [x] UI
  - [x] Light mode
  - [x] Dark mode
  - [ ] I18n
- Settings
  - [x] UI
  - [x] Light mode
  - [x] Dark mode
  - [ ] I18n
- Stats
  - [x] UI
  - [x] Light mode
  - [x] Dark mode
  - [ ] I18n
- About us
  - [x] UI
  - [x] Light mode
  - [x] Dark mode
  - [ ] I18n
- Sidebar
  - [x] UI
  - [x] Light mode
  - [x] Dark mode
  - [ ] I18n

**Comment by DanielHe4rt** [comment]
We can close this one for now since it's implemented. 

@moovmooov please open a new Pull Request with the missing i18n integration and a brief explanation of how to solve it.
