### ISSUE TITLE
Selects are behind the main element in the ARC Browser.

### ISSUE THREAD

**Issue by vinidotruan** [basementdevs/twitch-better-profile#59]
Hi guys, just to keep on track, on arc browser on v0.1.0(beta) all selects are like on the print, behind the main element.
I know that the most part of users are in firefox/chorme browsers, nothing serious I think.
![image](https://github.com/user-attachments/assets/fb9a0d3f-4017-4536-a9b4-d90e666cdbcc)

**Comment by DanielHe4rt** [comment]
We're not planning to backport any compatibility for ARC atm since the browser is receiving a lot of updates and still at bleeding edge phrase. 

Closing the issue.
