### ISSUE TITLE
fix: api doesn't return global settings when a custom channel isn't set

### ISSUE THREAD

**Issue by moovmooov** [basementdevs/twitch-better-profile#63]
According to #61 , we need to return the configuration that the user set, so for example if the user enabled the custom settings for a x channel, the API [https://twitch-extension.danielheart.dev/api/v1/settings/moovmooov?channel_id=danielhe4rt ](https://twitch-extension.danielheart.dev/api/v1/settings/moovmooov?channel_id=danielhe4rt ) will return the settings configured for this channel. 

The problem is that if the user doesn't have any custom settings set, the API returns nothing.
[https://twitch-extension.danielheart.dev/api/v1/settings/moovmooov?channel_id=ojogo ](https://twitch-extension.danielheart.dev/api/v1/settings/moovmooov?channel_id=ojogo )

**Comment by DanielHe4rt** [comment]
Fixed.
